### ISSUE TITLE
Manually deploy containerised version of demo app to kubernetes using git crypted secret

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform-user-docs#10]
**Estimate 5**

Co-ordinate with team 1 to use the method for deploying to the cluster that they are writing the documentation for. 

Our assumption is that kubernetes secret management will be the implementation for the run time secrets

**Comment by razvan-moj-zz** [comment]
Works, see 
https://django.apps.cloud-platforms-test.k8s.integration.dsd.io/
and
https://github.com/ministryofjustice/cloud-platform-reference-app/pull/6

**Comment by razvan-moj-zz** [comment]
dupe
