### ISSUE TITLE
Write the user documentation for how to add a secret to your application using git crypt

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform-user-docs#12]
**Estimate 2**

This will build on the #9 and #2

**Comment by kalbir** [comment]
@pwyborn The aim was to add this to https://ministryofjustice.github.io/cloud-platform-user-docs/ -- is that where you are aiming for at the end of this task?

**Comment by alkar** [comment]
#19 has been merged but I believe this issue actually refers to adding an application secret in the form of a kubernetes secret. Correct me if I'm wrong.

**Comment by kalbir** [comment]
This one is just for adding some basic git crypt usage, which I think is covered by this story so happy to move it to done.
