### ISSUE TITLE
Chronological automated test for adding a secret to an application

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform-user-docs#13]
**Estimate 3** 

Set up a test that runs every hour and works through the flow of adding a secret to the application.

**Comment by razvan-moj-zz** [comment]
An important note, when using secrets as params: "Parameters are all mandatory. There are no default values" - which means default/blank values must always be set or the pipeline fails before any 'run' step
Sample: https://github.com/ministryofjustice/cloud-platform-reference-app/blob/manual-app-deploy/cron-like-pipeline.yaml
To test:
pull branch manual-app-deploy
change credentials to something invalid with eg
```
$ kubectl -n development-concourse-main create -f secrets.txt
```
trigger pipeline:
```
$ fly -t sandbox set-pipeline -p secrets-test -c cron-like-pipeline.yaml
$ fly -t sandbox unpause-pipeline -p secrets-test
```

**Comment by razvan-moj-zz** [comment]
https://github.com/ministryofjustice/cloud-platform-reference-app/pull/20
