### ISSUE TITLE
Update the example app so that it uses a database

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform-user-docs#21]
Add functionality to the [reference app](https://github.com/ministryofjustice/cloud-platform-reference-app) so that it uses a postgres database.

Suggested functionlity is a form where:

* you can input your name
* the homepage shows all the names that have been input

**Comment by jasonBirchall** [comment]
This work was completed and merged under:
https://github.com/ministryofjustice/cloud-platform-reference-app/pull/32

**Comment by jasonBirchall** [comment]
This has now been reviewed. I'll move this to done.
