### ISSUE TITLE
Add postgres to helm chart for reference app

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform-user-docs#24]
Make it so that the helm chart for the [reference app](https://github.com/ministryofjustice/cloud-platform-reference-app) deploys a postgres and the reference app can connect to this postgres and do the things defined in #21.

**Comment by jasonBirchall** [comment]
Not sure why it didn't link. PR for this is here:
https://github.com/ministryofjustice/cloud-platform-reference-app/pull/38

**Comment by tatyree** [comment]
The trick is to put it in the PR description and prefix it with 'connects to'.
