### ISSUE TITLE
Write the documentation on how to add postgres to your app using helm

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform-user-docs#25]
connects to #22 

Tasks #22, #23, #24 make the reference app deployable with helm and make it use a postgres, also deployed with helm. This is writing the guide on:

* how you add postgres to your helm chart
* how you deploy the app _with postgres_ to the non-production cluster
* how you make sure they can connect to each other

**Comment by jasonBirchall** [comment]
Requires the Helm chart 'how to deploy' doc. Will speak with Ollie as to its progress.

**Comment by jasonBirchall** [comment]
PR here: 
https://github.com/ministryofjustice/cloud-platform-user-docs/pull/36
Kalbir to review.

**Comment by jasonBirchall** [comment]
Merged.
