### ISSUE TITLE
Get a template app into a Kubernetes deployable state

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform-user-docs#3]
#### Estimate 2

Checklist: 
- [x] Create a demo Django app
- [x] Containerise 
- [x] Push to ECR
- [x] Configure manifest files

**Comment by jasonBirchall** [comment]
App now built and ready for review. Missing a few links in the README, which have been substituted with ----ADD LINK----. Docs for the missing links have not yet been created.

**Comment by jasonBirchall** [comment]
Has now been reviewed and merged to master.
