### ISSUE TITLE
Write the circleCI user guide for how to deploy the demo app

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform-user-docs#33]
This ticket connects to #46
Should include details on how a user creates a service account.

**Comment by nayoa** [comment]
Please see the summary explaining about base64 decoding ca.crt and tokens for the ServiceAccount - 

https://github.com/ministryofjustice/cloud-platform-reference-app/pull/51

**Comment by nayoa** [comment]
Documentation so far - https://github.com/ministryofjustice/cloud-platform-user-docs/blob/add/serviceaccount/02-deploying-an-app/004-use-circleci-to-upgrade-app.md

**Comment by razvan-moj-zz** [comment]
finished in https://github.com/ministryofjustice/cloud-platform-user-docs/pull/46
