### ISSUE TITLE
Prep testcluster for test deployment

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform-user-docs#7]
#### Estimate 3

Checklist:

- [x] External DNS
- [x] Nginx Ingress
- [x] Kerberos 
- [x] Automatic namespacing

**Comment by jasonBirchall** [comment]
If you want to auth, please grab your config file here: login.apps.cloud-platforms-test.k8s.integration.dsd.io

**Comment by jasonBirchall** [comment]
Built the namespace automation in codebuild/pipeline. Attempted to rebuild for concourse but there were too many failures and not enough time. Will revisit this at another time. 

Repo for env creation is here: 
https://github.com/ministryofjustice/cloud-platform-test-cluster-env
