### ISSUE TITLE
Document developer workflow for managing secrets with demo app

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform-user-docs#9]
**Estimate 2** 

We will use git-crypt as the initial method to encrypt application secrets. We think similar documentation already exists in confluence.

Add documentation on the following to the [cloud platform user docs](https://ministryofjustice.github.io/cloud-platform-user-docs/)
- [ ] Installing GPG
- [ ] Installing git crypt
- [ ] Generating keys
- [ ] Pushing keys

**Comment by kerin** [comment]
We should also make sure the docs reference what to do if you already have a GPG key as a lot (most?) developers already do.

**Comment by pwyborn** [comment]
Please see https://github.com/ministryofjustice/cloud-platform-user-docs/pull/28.
